package com.sam.web.keqq.model;

public class LessonSource implements PrimaryKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lesson_source.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lesson_source.short_name
     *
     * @mbggenerated
     */
    private String short_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lesson_source.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lesson_source.site
     *
     * @mbggenerated
     */
    private String site;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lesson_source.owner
     *
     * @mbggenerated
     */
    private Integer owner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lesson_source.aid
     *
     * @mbggenerated
     */
    private Integer aid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lesson_source.service_qq
     *
     * @mbggenerated
     */
    private Integer service_qq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lesson_source.total_signed
     *
     * @mbggenerated
     */
    private Integer total_signed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lesson_source.teacher_num
     *
     * @mbggenerated
     */
    private Integer teacher_num;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lesson_source.id
     *
     * @return the value of lesson_source.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lesson_source.id
     *
     * @param id the value for lesson_source.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lesson_source.short_name
     *
     * @return the value of lesson_source.short_name
     *
     * @mbggenerated
     */
    public String getShort_name() {
        return short_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lesson_source.short_name
     *
     * @param short_name the value for lesson_source.short_name
     *
     * @mbggenerated
     */
    public void setShort_name(String short_name) {
        this.short_name = short_name == null ? null : short_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lesson_source.name
     *
     * @return the value of lesson_source.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lesson_source.name
     *
     * @param name the value for lesson_source.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lesson_source.site
     *
     * @return the value of lesson_source.site
     *
     * @mbggenerated
     */
    public String getSite() {
        return site;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lesson_source.site
     *
     * @param site the value for lesson_source.site
     *
     * @mbggenerated
     */
    public void setSite(String site) {
        this.site = site == null ? null : site.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lesson_source.owner
     *
     * @return the value of lesson_source.owner
     *
     * @mbggenerated
     */
    public Integer getOwner() {
        return owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lesson_source.owner
     *
     * @param owner the value for lesson_source.owner
     *
     * @mbggenerated
     */
    public void setOwner(Integer owner) {
        this.owner = owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lesson_source.aid
     *
     * @return the value of lesson_source.aid
     *
     * @mbggenerated
     */
    public Integer getAid() {
        return aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lesson_source.aid
     *
     * @param aid the value for lesson_source.aid
     *
     * @mbggenerated
     */
    public void setAid(Integer aid) {
        this.aid = aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lesson_source.service_qq
     *
     * @return the value of lesson_source.service_qq
     *
     * @mbggenerated
     */
    public Integer getService_qq() {
        return service_qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lesson_source.service_qq
     *
     * @param service_qq the value for lesson_source.service_qq
     *
     * @mbggenerated
     */
    public void setService_qq(Integer service_qq) {
        this.service_qq = service_qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lesson_source.total_signed
     *
     * @return the value of lesson_source.total_signed
     *
     * @mbggenerated
     */
    public Integer getTotal_signed() {
        return total_signed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lesson_source.total_signed
     *
     * @param total_signed the value for lesson_source.total_signed
     *
     * @mbggenerated
     */
    public void setTotal_signed(Integer total_signed) {
        this.total_signed = total_signed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lesson_source.teacher_num
     *
     * @return the value of lesson_source.teacher_num
     *
     * @mbggenerated
     */
    public Integer getTeacher_num() {
        return teacher_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lesson_source.teacher_num
     *
     * @param teacher_num the value for lesson_source.teacher_num
     *
     * @mbggenerated
     */
    public void setTeacher_num(Integer teacher_num) {
        this.teacher_num = teacher_num;
    }

    @Override
    public String toString() {
        return "LessonSource{" +
                "id=" + id +
                ", short_name='" + short_name + '\'' +
                ", name='" + name + '\'' +
                ", site='" + site + '\'' +
                ", owner=" + owner +
                ", aid=" + aid +
                ", service_qq=" + service_qq +
                ", total_signed=" + total_signed +
                ", teacher_num=" + teacher_num +
                '}';
    }
}