package com.sam.web.keqq.dao;

import com.sam.web.keqq.model.Lesson;

import java.util.List;
import java.util.Map;

public interface LessonMapper extends Mapper<Lesson> {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lesson
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lesson
     *
     * @mbggenerated
     */
    int insert(Lesson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lesson
     *
     * @mbggenerated
     */
    int insertSelective(Lesson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lesson
     *
     * @mbggenerated
     */
    Lesson selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lesson
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Lesson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lesson
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Lesson record);

    List<Lesson> selectAllSource();

}