package com.sam.web.keqq.dao;

import com.sam.web.keqq.model.LessonSource;

public interface LessonSourceMapper extends Mapper<LessonSource> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lesson_source
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lesson_source
     *
     * @mbggenerated
     */
    int insert(LessonSource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lesson_source
     *
     * @mbggenerated
     */
    int insertSelective(LessonSource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lesson_source
     *
     * @mbggenerated
     */
    LessonSource selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lesson_source
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(LessonSource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lesson_source
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LessonSource record);
}