package com.sam.web.keqq.dao;

import com.sam.web.keqq.model.LessonSource;

import java.util.List;
import java.util.Map;

/**
 * @author xiads
 * @date 23/01/2018
 * @since
 */
public interface Mapper<T> {

    boolean exists(T data);

    List<T> selectByParam(Map<String, Object> params);

    T selectByName(T data);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lesson_source
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    int insert(T data);

    int insertSelective(T data);

    T selectByPrimaryKey(Integer id);

    int updateByPrimaryKeySelective(T data);

    int updateByPrimaryKey(T data);
}
