package com.sam.web.mizhu.model;

import java.math.BigDecimal;

public class Good {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good.good_no
     *
     * @mbggenerated
     */
    private String goodNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good.brand_id
     *
     * @mbggenerated
     */
    private Integer brandId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good.category_id
     *
     * @mbggenerated
     */
    private Integer categoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good.series_id
     *
     * @mbggenerated
     */
    private Integer seriesId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good.produce_area
     *
     * @mbggenerated
     */
    private String produceArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good.instruction
     *
     * @mbggenerated
     */
    private String instruction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good.model
     *
     * @mbggenerated
     */
    private String model;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good.special
     *
     * @mbggenerated
     */
    private Integer special;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good.len
     *
     * @mbggenerated
     */
    private Integer len;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good.width
     *
     * @mbggenerated
     */
    private Integer width;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good.unit_id
     *
     * @mbggenerated
     */
    private Integer unitId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good.sub_unit_id
     *
     * @mbggenerated
     */
    private Integer subUnitId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good.image_url
     *
     * @mbggenerated
     */
    private String imageUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good.price
     *
     * @mbggenerated
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good.cost
     *
     * @mbggenerated
     */
    private BigDecimal cost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good.second_cost
     *
     * @mbggenerated
     */
    private BigDecimal secondCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good.measure
     *
     * @mbggenerated
     */
    private Integer measure;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good.stock
     *
     * @mbggenerated
     */
    private Integer stock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good.order
     *
     * @mbggenerated
     */
    private Integer order;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good.shelves_time
     *
     * @mbggenerated
     */
    private Integer shelvesTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good.top_time
     *
     * @mbggenerated
     */
    private Integer topTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good.cost_price
     *
     * @mbggenerated
     */
    private BigDecimal costPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good.valid
     *
     * @mbggenerated
     */
    private Integer valid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good.click_num
     *
     * @mbggenerated
     */
    private Integer clickNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good.custom
     *
     * @mbggenerated
     */
    private Integer custom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good.rate
     *
     * @mbggenerated
     */
    private Float rate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good.create_time
     *
     * @mbggenerated
     */
    private Integer createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good.create_id
     *
     * @mbggenerated
     */
    private Integer createId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good.modify_time
     *
     * @mbggenerated
     */
    private Integer modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good.modify_id
     *
     * @mbggenerated
     */
    private Integer modifyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good.id
     *
     * @return the value of good.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good.id
     *
     * @param id the value for good.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good.name
     *
     * @return the value of good.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good.name
     *
     * @param name the value for good.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good.good_no
     *
     * @return the value of good.good_no
     *
     * @mbggenerated
     */
    public String getGoodNo() {
        return goodNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good.good_no
     *
     * @param goodNo the value for good.good_no
     *
     * @mbggenerated
     */
    public void setGoodNo(String goodNo) {
        this.goodNo = goodNo == null ? null : goodNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good.brand_id
     *
     * @return the value of good.brand_id
     *
     * @mbggenerated
     */
    public Integer getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good.brand_id
     *
     * @param brandId the value for good.brand_id
     *
     * @mbggenerated
     */
    public void setBrandId(Integer brandId) {
        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good.category_id
     *
     * @return the value of good.category_id
     *
     * @mbggenerated
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good.category_id
     *
     * @param categoryId the value for good.category_id
     *
     * @mbggenerated
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good.series_id
     *
     * @return the value of good.series_id
     *
     * @mbggenerated
     */
    public Integer getSeriesId() {
        return seriesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good.series_id
     *
     * @param seriesId the value for good.series_id
     *
     * @mbggenerated
     */
    public void setSeriesId(Integer seriesId) {
        this.seriesId = seriesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good.produce_area
     *
     * @return the value of good.produce_area
     *
     * @mbggenerated
     */
    public String getProduceArea() {
        return produceArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good.produce_area
     *
     * @param produceArea the value for good.produce_area
     *
     * @mbggenerated
     */
    public void setProduceArea(String produceArea) {
        this.produceArea = produceArea == null ? null : produceArea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good.instruction
     *
     * @return the value of good.instruction
     *
     * @mbggenerated
     */
    public String getInstruction() {
        return instruction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good.instruction
     *
     * @param instruction the value for good.instruction
     *
     * @mbggenerated
     */
    public void setInstruction(String instruction) {
        this.instruction = instruction == null ? null : instruction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good.model
     *
     * @return the value of good.model
     *
     * @mbggenerated
     */
    public String getModel() {
        return model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good.model
     *
     * @param model the value for good.model
     *
     * @mbggenerated
     */
    public void setModel(String model) {
        this.model = model == null ? null : model.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good.special
     *
     * @return the value of good.special
     *
     * @mbggenerated
     */
    public Integer getSpecial() {
        return special;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good.special
     *
     * @param special the value for good.special
     *
     * @mbggenerated
     */
    public void setSpecial(Integer special) {
        this.special = special;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good.len
     *
     * @return the value of good.len
     *
     * @mbggenerated
     */
    public Integer getLen() {
        return len;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good.len
     *
     * @param len the value for good.len
     *
     * @mbggenerated
     */
    public void setLen(Integer len) {
        this.len = len;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good.width
     *
     * @return the value of good.width
     *
     * @mbggenerated
     */
    public Integer getWidth() {
        return width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good.width
     *
     * @param width the value for good.width
     *
     * @mbggenerated
     */
    public void setWidth(Integer width) {
        this.width = width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good.unit_id
     *
     * @return the value of good.unit_id
     *
     * @mbggenerated
     */
    public Integer getUnitId() {
        return unitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good.unit_id
     *
     * @param unitId the value for good.unit_id
     *
     * @mbggenerated
     */
    public void setUnitId(Integer unitId) {
        this.unitId = unitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good.sub_unit_id
     *
     * @return the value of good.sub_unit_id
     *
     * @mbggenerated
     */
    public Integer getSubUnitId() {
        return subUnitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good.sub_unit_id
     *
     * @param subUnitId the value for good.sub_unit_id
     *
     * @mbggenerated
     */
    public void setSubUnitId(Integer subUnitId) {
        this.subUnitId = subUnitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good.image_url
     *
     * @return the value of good.image_url
     *
     * @mbggenerated
     */
    public String getImageUrl() {
        return imageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good.image_url
     *
     * @param imageUrl the value for good.image_url
     *
     * @mbggenerated
     */
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl == null ? null : imageUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good.price
     *
     * @return the value of good.price
     *
     * @mbggenerated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good.price
     *
     * @param price the value for good.price
     *
     * @mbggenerated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good.cost
     *
     * @return the value of good.cost
     *
     * @mbggenerated
     */
    public BigDecimal getCost() {
        return cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good.cost
     *
     * @param cost the value for good.cost
     *
     * @mbggenerated
     */
    public void setCost(BigDecimal cost) {
        this.cost = cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good.second_cost
     *
     * @return the value of good.second_cost
     *
     * @mbggenerated
     */
    public BigDecimal getSecondCost() {
        return secondCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good.second_cost
     *
     * @param secondCost the value for good.second_cost
     *
     * @mbggenerated
     */
    public void setSecondCost(BigDecimal secondCost) {
        this.secondCost = secondCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good.measure
     *
     * @return the value of good.measure
     *
     * @mbggenerated
     */
    public Integer getMeasure() {
        return measure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good.measure
     *
     * @param measure the value for good.measure
     *
     * @mbggenerated
     */
    public void setMeasure(Integer measure) {
        this.measure = measure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good.stock
     *
     * @return the value of good.stock
     *
     * @mbggenerated
     */
    public Integer getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good.stock
     *
     * @param stock the value for good.stock
     *
     * @mbggenerated
     */
    public void setStock(Integer stock) {
        this.stock = stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good.status
     *
     * @return the value of good.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good.status
     *
     * @param status the value for good.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good.order
     *
     * @return the value of good.order
     *
     * @mbggenerated
     */
    public Integer getOrder() {
        return order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good.order
     *
     * @param order the value for good.order
     *
     * @mbggenerated
     */
    public void setOrder(Integer order) {
        this.order = order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good.shelves_time
     *
     * @return the value of good.shelves_time
     *
     * @mbggenerated
     */
    public Integer getShelvesTime() {
        return shelvesTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good.shelves_time
     *
     * @param shelvesTime the value for good.shelves_time
     *
     * @mbggenerated
     */
    public void setShelvesTime(Integer shelvesTime) {
        this.shelvesTime = shelvesTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good.top_time
     *
     * @return the value of good.top_time
     *
     * @mbggenerated
     */
    public Integer getTopTime() {
        return topTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good.top_time
     *
     * @param topTime the value for good.top_time
     *
     * @mbggenerated
     */
    public void setTopTime(Integer topTime) {
        this.topTime = topTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good.cost_price
     *
     * @return the value of good.cost_price
     *
     * @mbggenerated
     */
    public BigDecimal getCostPrice() {
        return costPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good.cost_price
     *
     * @param costPrice the value for good.cost_price
     *
     * @mbggenerated
     */
    public void setCostPrice(BigDecimal costPrice) {
        this.costPrice = costPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good.valid
     *
     * @return the value of good.valid
     *
     * @mbggenerated
     */
    public Integer getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good.valid
     *
     * @param valid the value for good.valid
     *
     * @mbggenerated
     */
    public void setValid(Integer valid) {
        this.valid = valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good.click_num
     *
     * @return the value of good.click_num
     *
     * @mbggenerated
     */
    public Integer getClickNum() {
        return clickNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good.click_num
     *
     * @param clickNum the value for good.click_num
     *
     * @mbggenerated
     */
    public void setClickNum(Integer clickNum) {
        this.clickNum = clickNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good.custom
     *
     * @return the value of good.custom
     *
     * @mbggenerated
     */
    public Integer getCustom() {
        return custom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good.custom
     *
     * @param custom the value for good.custom
     *
     * @mbggenerated
     */
    public void setCustom(Integer custom) {
        this.custom = custom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good.rate
     *
     * @return the value of good.rate
     *
     * @mbggenerated
     */
    public Float getRate() {
        return rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good.rate
     *
     * @param rate the value for good.rate
     *
     * @mbggenerated
     */
    public void setRate(Float rate) {
        this.rate = rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good.create_time
     *
     * @return the value of good.create_time
     *
     * @mbggenerated
     */
    public Integer getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good.create_time
     *
     * @param createTime the value for good.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Integer createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good.create_id
     *
     * @return the value of good.create_id
     *
     * @mbggenerated
     */
    public Integer getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good.create_id
     *
     * @param createId the value for good.create_id
     *
     * @mbggenerated
     */
    public void setCreateId(Integer createId) {
        this.createId = createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good.modify_time
     *
     * @return the value of good.modify_time
     *
     * @mbggenerated
     */
    public Integer getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good.modify_time
     *
     * @param modifyTime the value for good.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(Integer modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good.modify_id
     *
     * @return the value of good.modify_id
     *
     * @mbggenerated
     */
    public Integer getModifyId() {
        return modifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good.modify_id
     *
     * @param modifyId the value for good.modify_id
     *
     * @mbggenerated
     */
    public void setModifyId(Integer modifyId) {
        this.modifyId = modifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good.content
     *
     * @return the value of good.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good.content
     *
     * @param content the value for good.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    @Override
    public String toString() {
        return "Good{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", goodNo='" + goodNo + '\'' +
                ", brandId=" + brandId +
                ", categoryId=" + categoryId +
                ", seriesId=" + seriesId +
                ", produceArea='" + produceArea + '\'' +
                ", instruction='" + instruction + '\'' +
                ", model='" + model + '\'' +
                ", special=" + special +
                ", len=" + len +
                ", width=" + width +
                ", unitId=" + unitId +
                ", subUnitId=" + subUnitId +
                ", imageUrl='" + imageUrl + '\'' +
                ", price=" + price +
                ", cost=" + cost +
                ", secondCost=" + secondCost +
                ", measure=" + measure +
                ", stock=" + stock +
                ", status='" + status + '\'' +
                ", order=" + order +
                ", shelvesTime=" + shelvesTime +
                ", topTime=" + topTime +
                ", costPrice=" + costPrice +
                ", valid=" + valid +
                ", clickNum=" + clickNum +
                ", custom=" + custom +
                ", rate=" + rate +
                ", createTime=" + createTime +
                ", createId=" + createId +
                ", modifyTime=" + modifyTime +
                ", modifyId=" + modifyId +
                ", content='" + content + '\'' +
                '}';
    }
}