package com.sam.web.mizhu.model;

import java.math.BigDecimal;

public class Image {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.related_id
     *
     * @mbggenerated
     */
    private Integer relatedId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.style
     *
     * @mbggenerated
     */
    private Integer style;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.image_url
     *
     * @mbggenerated
     */
    private String imageUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.big_url
     *
     * @mbggenerated
     */
    private String bigUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.small_url
     *
     * @mbggenerated
     */
    private String smallUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.pic_name
     *
     * @mbggenerated
     */
    private String picName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.valid
     *
     * @mbggenerated
     */
    private Integer valid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.money
     *
     * @mbggenerated
     */
    private BigDecimal money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.id
     *
     * @return the value of image.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.id
     *
     * @param id the value for image.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.related_id
     *
     * @return the value of image.related_id
     *
     * @mbggenerated
     */
    public Integer getRelatedId() {
        return relatedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.related_id
     *
     * @param relatedId the value for image.related_id
     *
     * @mbggenerated
     */
    public void setRelatedId(Integer relatedId) {
        this.relatedId = relatedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.style
     *
     * @return the value of image.style
     *
     * @mbggenerated
     */
    public Integer getStyle() {
        return style;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.style
     *
     * @param style the value for image.style
     *
     * @mbggenerated
     */
    public void setStyle(Integer style) {
        this.style = style;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.image_url
     *
     * @return the value of image.image_url
     *
     * @mbggenerated
     */
    public String getImageUrl() {
        return imageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.image_url
     *
     * @param imageUrl the value for image.image_url
     *
     * @mbggenerated
     */
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl == null ? null : imageUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.big_url
     *
     * @return the value of image.big_url
     *
     * @mbggenerated
     */
    public String getBigUrl() {
        return bigUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.big_url
     *
     * @param bigUrl the value for image.big_url
     *
     * @mbggenerated
     */
    public void setBigUrl(String bigUrl) {
        this.bigUrl = bigUrl == null ? null : bigUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.small_url
     *
     * @return the value of image.small_url
     *
     * @mbggenerated
     */
    public String getSmallUrl() {
        return smallUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.small_url
     *
     * @param smallUrl the value for image.small_url
     *
     * @mbggenerated
     */
    public void setSmallUrl(String smallUrl) {
        this.smallUrl = smallUrl == null ? null : smallUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.pic_name
     *
     * @return the value of image.pic_name
     *
     * @mbggenerated
     */
    public String getPicName() {
        return picName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.pic_name
     *
     * @param picName the value for image.pic_name
     *
     * @mbggenerated
     */
    public void setPicName(String picName) {
        this.picName = picName == null ? null : picName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.valid
     *
     * @return the value of image.valid
     *
     * @mbggenerated
     */
    public Integer getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.valid
     *
     * @param valid the value for image.valid
     *
     * @mbggenerated
     */
    public void setValid(Integer valid) {
        this.valid = valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.money
     *
     * @return the value of image.money
     *
     * @mbggenerated
     */
    public BigDecimal getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.money
     *
     * @param money the value for image.money
     *
     * @mbggenerated
     */
    public void setMoney(BigDecimal money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.remark
     *
     * @return the value of image.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.remark
     *
     * @param remark the value for image.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    @Override
    public String toString() {
        return "Image{" +
                "id=" + id +
                ", relatedId=" + relatedId +
                ", style=" + style +
                ", imageUrl='" + imageUrl + '\'' +
                ", bigUrl='" + bigUrl + '\'' +
                ", smallUrl='" + smallUrl + '\'' +
                ", picName='" + picName + '\'' +
                ", valid=" + valid +
                ", money=" + money +
                ", remark='" + remark + '\'' +
                '}';
    }
}